version: '3'
services:
  frontend:
    image: vhmds/movie-frontend
    ports:
      - "80:3000"
    enviroment:
      - BACKEND_URL: backend:8080
    depends_on:
      - backend
  backend:
    image: vhmds/movie-review
    ports:
      - "8000:8080"
